# Managed by Noctalia user templates.

typeset -gA ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='fg={{colors.on_surface.default.hex}}'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{colors.error.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{colors.secondary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{colors.outline.default.hex}}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[path]='fg={{colors.tertiary.default.hex}},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={{colors.tertiary_container.default.hex}}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={{colors.error.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg={{colors.primary_container.default.hex}}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[process-substitution]='fg={{colors.primary_container.default.hex}}'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={{colors.on_primary_container.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{colors.secondary_container.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg={{colors.secondary_container.default.hex}}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{colors.on_surface_variant.default.hex}}'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={{colors.on_surface.default.hex}}'
