firefox	Firefox	1	browser-firefox,browser-firefox-pywalfox	Arch official Firefox
chromium	Chromium	0	browser-chromium	Arch official Chromium
brave	Brave	0	browser-brave	Brave from AUR
zen-aur	Zen Browser AUR	0	browser-zen-aur	Zen from AUR
zen-flatpak	Zen Browser Flatpak	0	browser-zen-flatpak	Zen from Flathub
helium	Helium Browser AUR	0	browser-helium	Experimental Helium from AUR
