firefox	Firefox	1		packages/arch/official/browsers/firefox.pkgs	Arch official Firefox
chromium	Chromium	0		packages/arch/official/browsers/chromium.pkgs	Arch official Chromium
brave	Brave	0	aur	packages/arch/aur/browsers/brave.pkgs	Brave from AUR
zen-aur	Zen Browser AUR	0	aur	packages/arch/aur/browsers/zen.pkgs	Zen from AUR
zen-flatpak	Zen Browser Flatpak	0	flathub	packages/arch/flatpak/browsers.flatpaks	Zen from Flathub
helium	Helium Browser AUR	0	aur	packages/arch/aur/browsers/helium.pkgs	Experimental Helium from AUR

