communication	Communication apps	0	flathub	packages/arch/flatpak/communication.flatpaks	Optional communication Flatpaks
creative	Creative apps	0	flathub	packages/arch/flatpak/creative.flatpaks	Optional creative Flatpaks

