steam	Steam	0	multilib	packages/arch/official/gaming/base.pkgs	Steam and related gaming tools
game-tools	GameMode Gamescope MangoHud	0		packages/arch/official/gaming/base.pkgs	Game performance tools
lutris	Lutris	0		packages/arch/official/gaming/lutris.pkgs	Lutris package
heroic	Heroic Games Launcher	0	aur	packages/arch/aur/gaming/heroic.pkgs	Heroic from AUR

