firefox	Firefox	0	browser-firefox	Fedora official Firefox
chromium	Chromium	0	browser-chromium	Fedora official Chromium
chrome	Google Chrome	0	browser-chrome	Google Chrome from Google RPM repo
brave	Brave	0	browser-brave	Brave from official Brave RPM repo
zen-flatpak	Zen Browser Flatpak	0	browser-zen-flatpak	Zen from Flathub
zen-copr	Zen Browser COPR	0	browser-zen-copr	Zen from Fedora COPR
helium-copr	Helium Browser COPR	0	browser-helium-copr	Experimental Helium from COPR
