vscode	Visual Studio Code	0	dev-vscode	Visual Studio Code from Microsoft RPM repo
neovim	Neovim	0	dev-neovim	Terminal editor
jetbrains-toolbox	JetBrains Toolbox	0	dev-jetbrains-toolbox	JetBrains Toolbox App
docker	Docker CE	0	dev-docker	Docker Engine from the official Docker repo
devtunnel	Microsoft Dev Tunnel CLI	0	dev-devtunnel	Microsoft Dev Tunnel CLI
lazygit	lazygit	0	dev-lazygit	Git terminal UI
lazydocker	lazydocker	0	dev-lazydocker	Docker terminal UI from Homebrew
