communication	Communication apps	0	flathub	packages/fedora/flatpak/communication.flatpaks	Optional communication Flatpaks
creative	Creative apps	0	flathub	packages/fedora/flatpak/creative.flatpaks	Optional creative Flatpaks

