rpmfusion-free	RPM Fusion Free repo	0	rpmfusion-free		Enable RPM Fusion Free
rpmfusion-nonfree	RPM Fusion Nonfree repo	0	rpmfusion-nonfree		Enable RPM Fusion Nonfree
codecs	Full multimedia codecs	0	rpmfusion-free,rpmfusion-nonfree	packages/fedora/rpmfusion/media.pkgs	Install multimedia codec support

