onlyoffice	OnlyOffice	0	office-onlyoffice	OnlyOffice from Flathub
teams	Teams for Linux	0	office-teams	Teams for Linux from Flathub
zoom	Zoom	0	office-zoom	Zoom from Flathub
pinta	Pinta	0	office-pinta	Pinta from Flathub
inkscape	Inkscape	0	office-inkscape	Inkscape from Flathub
